[build]

command = "npm run build"
  publish = "dist/"
[build.environment]

BUILD_TARGET = "DEFAULT"
NODE_ENV = "production"

[context.demo]

command = "npm run build"
# environment = {BUILD_TARGET = "DEMO", NODE_ENV = "production"}
publish = "dist/"

[context.demo.environment]

BUILD_TARGET = "DEMO"
NODE_ENV = "production"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
