[build]

command = "npm install --legacy-peer-deps && node ./create-env.js && npm run build --legacy-peer-deps"
publish = "dist/"

[build.environment]

BUILD_TARGET = "DEFAULT"

[context.demo]

command = "node ./create-env.js && npm run build"
# environment = {BUILD_TARGET = "DEMO", NODE_ENV = "production"}
publish = "dist/"

[context.demo.environment]

BUILD_TARGET = "DEMO"

[context.deploy-preview.environment]
API_ENDPOINT="https://leipzig-trees-express-now.vercel.app" # DEV

[context.branch-deploy.environment]
API_ENDPOINT="https://leipzig-trees-express-now.vercel.app" # DEV

[context.staging.environment]
API_ENDPOINT="https://leipzig-trees-express-now.vercel.app" # DEV

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
