[build]

<<<<<<< HEAD
command = "node ./create-env.js && npm install && npm run build"
publish = "dist/"
=======
command = "node ./create-env.js && webpack --config webpack/prod.config.js && echo '/* /index.html 200' | cat >dist/_redirects"
>>>>>>> 017da9c... Use commands from node_modules/.bin

[build.environment]

BUILD_TARGET = "DEFAULT"

[context.demo]

command = "node ./create-env.js && webpack --config webpack/prod.config.js && echo '/* /index.html 200' | cat >dist/_redirects"
# environment = {BUILD_TARGET = "DEMO", NODE_ENV = "production"}
publish = "dist/"

[context.demo.environment]

BUILD_TARGET = "DEMO"

[context.deploy-preview.environment]
API_ENDPOINT="https://giessdenkiez-de-postgres-api-git-dev-technologiestiftung1.vercel.app" # DEV

[context.branch-deploy.environment]
API_ENDPOINT="https://giessdenkiez-de-postgres-api-git-dev-technologiestiftung1.vercel.app" # DEV

[context.staging.environment]
API_ENDPOINT="https://giessdenkiez-de-postgres-api-git-dev-technologiestiftung1.vercel.app" # DEV

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
